name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'taskflow-web/**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.22.3'
          cache: 'npm'
          cache-dependency-path: './taskflow-web/package-lock.json'
      - name: Install dependencies
        working-directory: ./taskflow-web
        run: npm ci
      - name: Build Angular
        working-directory: ./taskflow-web
        run: npm run build

      - name: Verify build output
        run: |
          echo "Build output:"
          ls -la ./taskflow-web/dist/taskflow-web/browser
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_FOREST_03B8A7F00 }}
          action: upload
          app_location: "./taskflow-web/dist/taskflow-web/browser"
          skip_app_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_FOREST_03B8A7F00 }}
          action: "close"
